2017-05-09 09:39:36,760 [6] ERROR LeaRun.DataAccess.DbHelper - 列名 'res_kf' 无效。
2017-05-09 09:40:15,091 [6] ERROR LeaRun.DataAccess.DbHelper - 列名 'res_kf' 无效。
2017-05-09 09:41:11,573 [6] ERROR LeaRun.DataAccess.DbHelper - 列名 'res_kf' 无效。
2017-05-09 09:45:43,029 [15] ERROR LeaRun.DataAccess.DbHelper - 列名 'res_kf' 无效。
2017-05-09 10:40:42,240 [11] ERROR LeaRun.DataAccess.DbHelper - 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接)
2017-05-09 10:48:40,558 [8] ERROR LeaRun.DataAccess.DbHelper - 列名 'res_kf' 无效。
2017-05-09 10:49:10,457 [8] ERROR LeaRun.DataAccess.DbHelper - 列名 'res_kf' 无效。
2017-05-09 11:41:28,620 [7] ERROR LeaRun.DataAccess.DbHelper - SqlDateTime 溢出。必须介于 1/1/1753 12:00:00 AM 和 12/31/9999 11:59:59 PM 之间。
2017-05-09 11:42:22,574 [7] ERROR LeaRun.DataAccess.DbHelper - SqlDateTime 溢出。必须介于 1/1/1753 12:00:00 AM 和 12/31/9999 11:59:59 PM 之间。
