2017-05-05 09:34:29,691 [9] ERROR LeaRun.DataAccess.DbHelper - 列名 'resid' 无效。
2017-05-05 11:06:48,245 [67] ERROR LeaRun.DataAccess.DbHelper - 将截断字符串或二进制数据。
语句已终止。
2017-05-05 11:07:26,523 [76] ERROR LeaRun.DataAccess.DbHelper - 将截断字符串或二进制数据。
语句已终止。
2017-05-05 11:09:15,634 [67] ERROR LeaRun.DataAccess.DbHelper - 将截断字符串或二进制数据。
语句已终止。
2017-05-05 13:53:17,627 [186] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@res_id"。
2017-05-05 13:55:29,097 [193] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@res_id"。
2017-05-05 15:52:55,911 [9] ERROR LeaRun.DataAccess.DbHelper - 字符串 '000001' 后的引号不完整。
'000001' 附近有语法错误。
2017-05-05 17:22:11,185 [10] ERROR LeaRun.DataAccess.DbHelper - '2017' 附近有语法错误。
2017-05-05 17:22:18,690 [9] ERROR LeaRun.DataAccess.DbHelper - '2017' 附近有语法错误。
2017-05-05 17:22:51,209 [10] ERROR LeaRun.DataAccess.DbHelper - '2017' 附近有语法错误。
2017-05-05 17:23:46,042 [10] ERROR LeaRun.DataAccess.DbHelper - 找不到存储过程 'RapidMonthlyReport 2017 '。
2017-05-05 17:25:24,692 [10] ERROR LeaRun.DataAccess.DbHelper - 找不到存储过程 'RapidMonthlyReport 2017 '。
2017-05-05 17:28:45,612 [10] ERROR LeaRun.DataAccess.DbHelper - 找不到存储过程 'RapidMonthlyReport @keyword '。
2017-05-05 17:32:45,216 [9] ERROR LeaRun.DataAccess.DbHelper - 对象名 '##list' 无效。
2017-05-05 17:34:10,565 [9] ERROR LeaRun.DataAccess.DbHelper - 列名 'res_id' 无效。
2017-05-05 17:39:24,669 [9] ERROR LeaRun.DataAccess.DbHelper - 找不到存储过程 'RapidMonthlyReport 2017 '。
2017-05-05 17:45:22,361 [9] ERROR LeaRun.DataAccess.DbHelper - 找不到存储过程 'RapidMonthlyReport @keyword'。
2017-05-05 17:46:26,975 [9] ERROR LeaRun.DataAccess.DbHelper - 找不到存储过程 'RapidMonthlyReport @keyword'。
2017-05-05 17:50:43,781 [9] ERROR LeaRun.DataAccess.DbHelper - 找不到存储过程 'exec RapidMonthlyReport @keyword'。
2017-05-05 17:53:15,062 [10] ERROR LeaRun.DataAccess.DbHelper - 过程或函数 'RapidMonthlyReport' 需要参数 '@Year'，但未提供该参数。
2017-05-05 17:53:32,731 [10] ERROR LeaRun.DataAccess.DbHelper - 过程或函数 'RapidMonthlyReport' 需要参数 '@Year'，但未提供该参数。
2017-05-05 18:04:38,328 [10] ERROR LeaRun.DataAccess.DbHelper - 过程或函数 'RapidMonthlyReport' 需要参数 '@Year'，但未提供该参数。
