2017-04-19 14:43:02,307 [9] ERROR LeaRun.DataAccess.DbHelper - 列名 'CompanyId' 无效。
列名 'DepartmentId' 无效。
列名 'SortCode' 无效。
2017-04-19 14:43:21,972 [15] ERROR LeaRun.DataAccess.DbHelper - 列名 'CompanyId' 无效。
列名 'DepartmentId' 无效。
列名 'SortCode' 无效。
2017-04-19 14:44:12,003 [7] ERROR LeaRun.DataAccess.DbHelper - 列名 'CompanyId' 无效。
列名 'DepartmentId' 无效。
列名 'SortCode' 无效。
2017-04-19 14:45:13,122 [9] ERROR LeaRun.DataAccess.DbHelper - 列名 'tesstid' 无效。
2017-04-19 14:56:31,932 [10] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@CompanyId nvarchar(4000))SELECT top 1 CompanyId,ParentId,Categ' 需要参数 '@CompanyId'，但未提供该参数。
2017-04-19 15:15:41,631 [11] ERROR LeaRun.DataAccess.DbHelper - 列名 'UserId' 无效。
2017-04-19 15:16:19,605 [7] ERROR LeaRun.DataAccess.DbHelper - 列名 'UserId' 无效。
2017-04-19 15:16:42,289 [12] ERROR LeaRun.DataAccess.DbHelper - 列名 'UserId' 无效。
2017-04-19 15:18:08,400 [12] ERROR LeaRun.DataAccess.DbHelper - 列名 'UserId' 无效。
2017-04-19 15:21:48,710 [13] ERROR LeaRun.DataAccess.DbHelper - 列名 'UserId' 无效。
2017-04-19 15:24:48,398 [26] ERROR LeaRun.DataAccess.DbHelper - 列名 'UserId' 无效。
2017-04-19 15:33:55,114 [24] ERROR LeaRun.DataAccess.DbHelper - 当 IDENTITY_INSERT 设置为 OFF 时，不能为表 'TestTable' 中的标识列插入显式值。
2017-04-19 15:35:47,454 [32] ERROR LeaRun.DataAccess.DbHelper - 当 IDENTITY_INSERT 设置为 OFF 时，不能为表 'TestTable' 中的标识列插入显式值。
2017-04-19 15:39:11,134 [32] ERROR LeaRun.DataAccess.DbHelper - 当 IDENTITY_INSERT 设置为 OFF 时，不能为表 'TestTable' 中的标识列插入显式值。
