2017-05-18 08:36:20,770 [12] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@CompanyId nvarchar(4000))SELECT top 1 CompanyId,ParentId,Categ' 需要参数 '@CompanyId'，但未提供该参数。
2017-05-18 09:11:59,682 [8] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@CompanyId nvarchar(4000))SELECT top 1 CompanyId,ParentId,Categ' 需要参数 '@CompanyId'，但未提供该参数。
2017-05-18 14:59:03,366 [10] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@res_id"。
2017-05-18 15:02:44,490 [10] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@res_id"。
2017-05-18 15:09:03,642 [18] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@res_id"。
2017-05-18 15:10:36,927 [18] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@res_id"。
2017-05-18 15:11:02,668 [15] ERROR LeaRun.DataAccess.DbHelper - 将截断字符串或二进制数据。
语句已终止。
2017-05-18 15:13:03,734 [15] ERROR LeaRun.DataAccess.DbHelper - 将截断字符串或二进制数据。
语句已终止。
