2017-05-04 08:42:33,608 [9] ERROR LeaRun.DataAccess.DbHelper - 将截断字符串或二进制数据。
语句已终止。
2017-05-04 08:43:51,567 [10] ERROR LeaRun.DataAccess.DbHelper - 将截断字符串或二进制数据。
语句已终止。
2017-05-04 08:54:38,844 [38] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@res_id"。
2017-05-04 09:12:35,604 [10] ERROR LeaRun.DataAccess.DbHelper - 列名 'res_yzbdt' 无效。
列名 'res_yzbnode' 无效。
2017-05-04 10:13:49,114 [10] ERROR LeaRun.DataAccess.DbHelper - 列名 'res_bzgxdt' 无效。
列名 'res_bzgxnode' 无效。
列名 'res_bzgxfj' 无效。
2017-05-04 10:15:14,085 [8] ERROR LeaRun.DataAccess.DbHelper - 从 nvarchar 数据类型到 datetime 数据类型的转换产生一个超出范围的值。
语句已终止。
2017-05-04 10:18:30,514 [8] ERROR LeaRun.DataAccess.DbHelper - 从 nvarchar 数据类型到 datetime 数据类型的转换产生一个超出范围的值。
语句已终止。
2017-05-04 13:56:10,261 [6] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@CompanyId nvarchar(4000))SELECT top 1 CompanyId,ParentId,Categ' 需要参数 '@CompanyId'，但未提供该参数。
2017-05-04 16:43:08,844 [9] ERROR LeaRun.DataAccess.DbHelper - 列名 'System' 无效。
